### ISSUE TITLE
HighChart 라이브러리 이용

### ISSUE THREAD

**Issue by kimsehwan96** [kimsehwan96/Revolution-pi-view-app#18]
HighChart 라이브러를 이용해서 각 필드의 데이터 트렌드를 시각화 할 필요가 있음.

**Comment by HongKyungWon** [comment]
대용량 첨부 파일은 30일간 보관 / 100회까지 다운로드 가능




20200802_180424.mp4 903MB


  다운로드 기간: 2020/08/02 ~ 2020/09/01






​
​
-----Original Message-----
